// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Key struct {
	KeyID     int64
	Key       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Cache     bool
	Storage   bool
	ExpiresAt int64
	ID        string
}

type Service struct {
	Sid         int64
	UserID      int64
	ServiceUuid pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	KeyID       int64
	Name        string
}

type User struct {
	UserID    int64
	Email     string
	Password  string
	Role      int64
	UserUiid  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Confirmed bool
	Deleted   bool
	ClerkID   string
}
